version: "3.4"

services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      SERVER_NAME: php.local
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb:3306/${MYSQL_DATABASE}?serverVersion={MYSQL_VERSION}&charset={MYSQL_CHARSET}"      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 8080
        published: ${HTTP_PORT:-8080}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

      


  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

    ports:
      - "15672:15672"  # RabbitMQ management UI
      - "5672:5672"
    volumes:
      #- ./rabbitmq/config:/etc/rabbitmq
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia

  proxymanager:
    hostname : "proxymanager"
    image: luminati/luminati-proxy
    command: proxy-manager --config /var/lib/lpm-vol/_data/hl_423fed98_config.json
    ports:
      - "8085:22999" # Web console and API
      - "22226:22225" # Drop-in
      - "24001:24000" # First configurable proxy
    volumes:
      - ./proxymanager:/var/lib/lpm-vol/_data
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: avlulacjvaa
      MYSQL_DATABASE: db_test
      MYSQL_USER: armeldemarsac
      MYSQL_PASSWORD: avlulacjvaa
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: unless-stopped

  pythonscrapper:
    depends_on:
      - rabbitmq
    build: ./pythonscrapper
    ports:
      - "5000:80"
    volumes:
      - ./pythonscrapper:/var/lib/pythonscrapper



  

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
  mariadb_data:
  #lpm-vol:
  #rabbitmq_data:
  #pythonscrapper:
  
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
